import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, BarChart3, BookOpen, CalendarDays, ChevronRight, Compass, FileText, Filter, Grid2X2, MapPin, Menu, Network, Search, Shuffle, Sparkles, X } from 'lucide-react'
import { AnimatePresence, MotionConfig, motion } from 'framer-motion'
import { formatDate, formatTime, receipts } from './utils/dataAdapter'
import { getConnections } from './utils/connections'
import { getInsights } from './utils/insights'
import { getImageAlt, getReceiptImage } from './utils/imageMap'

const pageMeta = {
  overview: { label: 'Overview', eyebrow: 'Your life, in receipts', title: 'Your life, told through little moments.', description: 'Every receipt is a clue. Discover the relationships, rhythms, and stories hidden in everyday digital life.' },
  explore: { label: 'Explore receipts', eyebrow: 'The archive', title: 'Follow the small signals.', description: 'Browse the moments that make up the larger picture.' },
  timeline: { label: 'Timeline', eyebrow: 'In sequence', title: 'The days, as they happened.', description: 'A chronological view of the receipts, grouped into readable moments.' },
  connections: { label: 'Connections', eyebrow: 'Pattern finder', title: 'Where moments touch.', description: 'Transparent links built from shared evidence in the archive.' },
  chapters: { label: 'Story chapters', eyebrow: 'The story so far', title: 'A few chapters, gathered.', description: 'Descriptive groupings of receipts that sit close in place, time, or theme.' },
  insights: { label: 'Insights', eyebrow: 'The shape of the archive', title: 'What the receipts reveal.', description: 'A lightweight reading of categories, places, tags, and activity.' }
}

const categoryColor = { Music: 'moss', Places: 'clay', Photos: 'sky', Purchases: 'ochre', Messages: 'rose', Events: 'ink', Searches: 'sage', 'Personal Notes': 'violet', 'Movies & Entertainment': 'blue' }
const navItems = [
  { id: 'overview', label: 'Overview', icon: Grid2X2 },
  { id: 'explore', label: 'Explore', icon: Compass },
  { id: 'timeline', label: 'Timeline', icon: CalendarDays },
  { id: 'connections', label: 'Connections', icon: Network },
  { id: 'chapters', label: 'Story chapters', icon: BookOpen },
  { id: 'insights', label: 'Insights', icon: BarChart3 }
]

function App() {
  const [page, setPage] = useState('overview')
  const [selected, setSelected] = useState(null)
  const [mobileNav, setMobileNav] = useState(false)
  const [surpriseReceipt, setSurpriseReceipt] = useState(null)
  const insights = useMemo(() => getInsights(receipts), [])
  const navigate = (next) => { setPage(next); setMobileNav(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const surpriseMe = () => {
    if (!receipts.length) return
    const next = receipts[Math.floor(Math.random() * receipts.length)]
    setSurpriseReceipt(next.id)
    setSelected(next)
  }

  useEffect(() => {
    if (!selected) return undefined
    const closeOnEscape = (event) => event.key === 'Escape' && setSelected(null)
    document.addEventListener('keydown', closeOnEscape)
    const previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    return () => { document.removeEventListener('keydown', closeOnEscape); document.body.style.overflow = previousOverflow }
  }, [selected])

  return <MotionConfig reducedMotion="user"><div className="app-shell">
    <motion.aside className={`sidebar ${mobileNav ? 'is-open' : ''}`} animate={{ x: mobileNav ? 0 : 0 }} transition={{ duration: .3 }}>
      <div className="brand"><span className="brand-mark">↗</span><span>LifeLoop</span></div>
      <p className="brand-note">Your life,<br />in receipts.</p>
      <nav aria-label="Primary navigation">
        {navItems.map(({ id, label, icon: Icon }) => <motion.button key={id} className={`nav-item ${page === id ? 'active' : ''}`} onClick={() => navigate(id)} whileHover={{ x: 4 }} whileTap={{ scale: .98 }}><Icon size={17} strokeWidth={1.8} /><span>{label}</span>{page === id && <ChevronRight className="nav-arrow" size={15} />}</motion.button>)}
      </nav>
      <div className="sidebar-footer"><span className="status-dot" /> Local archive<br /><small>Development dataset</small></div>
    </motion.aside>
    {mobileNav && <button className="mobile-scrim" aria-label="Close navigation" onClick={() => setMobileNav(false)} />}
    <main className="main-content">
      <header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu size={21} /></button><div className="crumb">LifeLoop <span>/</span> {pageMeta[page].label}</div><div className="topbar-actions"><button className="surprise-button" onClick={surpriseMe}><Shuffle size={14} /> Surprise me</button><span className="archive-count"><span className="status-dot" /> {receipts.length} receipts</span><button className="icon-button" aria-label="Search receipts" onClick={() => navigate('explore')}><Search size={18} /></button></div></header>
      <AnimatePresence mode="wait"><motion.div key={page} className={`page-wrap page-${page}`} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .32, ease: 'easeOut' }}><PageHeader page={page} /><PageContent page={page} receipts={receipts} insights={insights} onNavigate={navigate} onSelect={setSelected} /></motion.div></AnimatePresence>
    </main>
    <AnimatePresence>{selected && <ReceiptModal receipt={selected} receipts={receipts} onClose={() => { setSelected(null); setSurpriseReceipt(null) }} onSelect={setSelected} surprised={Boolean(surpriseReceipt)} />}</AnimatePresence>
  </div></MotionConfig>
}

function PageHeader({ page }) {
  const meta = pageMeta[page]
  return <motion.div className="page-header" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .35, delay: .04 }}><p className="eyebrow">{meta.eyebrow}</p><h1>{meta.title}</h1><p className="page-description">{meta.description}</p></motion.div>
}

function PageContent({ page, receipts: items, insights, onNavigate, onSelect }) {
  if (page === 'overview') return <Overview receipts={items} insights={insights} onNavigate={onNavigate} onSelect={onSelect} />
  if (page === 'explore') return <Explore receipts={items} onSelect={onSelect} />
  if (page === 'timeline') return <Timeline receipts={items} onSelect={onSelect} />
  if (page === 'connections') return <Connections receipts={items} onSelect={onSelect} />
  if (page === 'chapters') return <Chapters receipts={items} onSelect={onSelect} onNavigate={onNavigate} />
  return <Insights receipts={items} insights={insights} />
}

function Overview({ receipts: items, insights, onNavigate, onSelect }) {
  const latest = [...items].sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 4)
  const categoryEntries = Object.entries(insights.categories).sort((a, b) => b[1] - a[1])
  return <>
    <section className="hero-panel"><motion.div className="hero-copy" initial={{ opacity: 0, x: -16 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .42, delay: .08 }}><span className="hero-kicker"><Sparkles size={14} /> A living archive</span><h2>Meaning hides<br /><em>in the margins.</em></h2><p>LifeLoop turns everyday digital traces into a story you can wander through, one connection at a time.</p><motion.button className="primary-button" onClick={() => onNavigate('explore')} whileHover={{ y: -3 }} whileTap={{ scale: .97 }}>Start exploring <ArrowUpRight size={16} /></motion.button></motion.div><motion.div className="hero-art" aria-label="Decorative category artwork" initial={{ opacity: 0, x: 16 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .48, delay: .18 }}><motion.img className="hero-image hero-image-back" src={getReceiptImage('Places')} alt={getImageAlt('Places', 'decorative scrapbook collage')} /><motion.img className="hero-image hero-image-mid" src={getReceiptImage('Music')} alt={getImageAlt('Music', 'decorative scrapbook collage')} /><motion.img className="hero-image hero-image-front" src={getReceiptImage('Photos')} alt={getImageAlt('Photos', 'decorative scrapbook collage')} whileHover={{ y: -8, rotate: 1 }} /><div className="hero-paper-note">Small moments.<br /><strong>Big stories.</strong></div><span className="art-caption">Decorative category artwork</span></motion.div></section>
    <div className="section-heading"><div><p className="eyebrow">At a glance</p><h2>The archive, so far</h2></div><button className="text-button" onClick={() => onNavigate('insights')}>View all insights <ArrowUpRight size={15} /></button></div>
    <motion.div className="stats-grid" variants={{ show: { transition: { staggerChildren: .07 } } }} initial="hidden" animate="show"><Stat label="Receipts collected" value={items.length} detail="across the archive" /><Stat label="Categories" value={categoryEntries.length} detail="different kinds of moments" /><Stat label="Places visited" value={new Set(items.map((item) => item.location).filter(Boolean)).size} detail="distinct locations" /><Stat label="Most active" value={categoryEntries[0]?.[0] || '—'} detail={categoryEntries[0] ? `${categoryEntries[0][1]} receipts` : 'no data'} compact /></motion.div>
    <div className="overview-grid"><section className="content-section"><div className="section-heading compact-heading"><div><p className="eyebrow">Recent memories</p><h2>Fresh from the archive</h2></div><button className="text-button" onClick={() => onNavigate('explore')}>See everything <ArrowUpRight size={15} /></button></div><div className="receipt-list">{latest.map((receipt) => <ReceiptRow key={receipt.id} receipt={receipt} onSelect={onSelect} />)}</div></section><aside className="story-teaser"><p className="eyebrow">Featured thread</p><div className="thread-icon"><BookOpen size={18} /></div><h3>The creative thread</h3><p>Four moments connect through a shared <strong>creative</strong> tag, moving from a notebook to a talk, a search, and a note.</p><button className="text-button" onClick={() => onNavigate('chapters')}>Read this chapter <ArrowUpRight size={15} /></button><div className="thread-line"><span /><span /><span /><span /></div></aside></div>
  </>
}

function Stat({ label, value, detail, compact }) { return <motion.article className={`stat-card ${compact ? 'stat-compact' : ''}`} variants={{ hidden: { opacity: 0, y: 12 }, show: { opacity: 1, y: 0 } }} whileHover={{ y: -4 }}><p>{label}</p><strong>{value}</strong><span>{detail}</span></motion.article> }
function ReceiptRow({ receipt, onSelect }) { return <button className="receipt-row" onClick={() => onSelect(receipt)}><span className={`category-dot ${categoryColor[receipt.category] || 'sage'}`} /><span className="row-main"><strong>{receipt.title}</strong><small>{receipt.category}{receipt.location ? ` · ${receipt.location}` : ''}</small></span><time>{formatDate(receipt.date, { month: 'short', day: 'numeric' })}</time><ChevronRight size={16} /></button> }

function Explore({ receipts: items, onSelect }) {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('All categories'); const [location, setLocation] = useState('All locations'); const [date, setDate] = useState(''); const [sort, setSort] = useState('newest')
  const categories = ['All categories', ...new Set(items.map((item) => item.category))]
  const locations = ['All locations', ...new Set(items.map((item) => item.location).filter(Boolean))]
  const filtered = items.filter((item) => { const text = `${item.title} ${item.description} ${item.location} ${item.tags.join(' ')}`.toLowerCase(); return (category === 'All categories' || item.category === category) && (location === 'All locations' || item.location === location) && (!date || String(item.date).slice(0, 10) === date) && text.includes(query.toLowerCase()) }).sort((a, b) => sort === 'newest' ? new Date(b.date) - new Date(a.date) : sort === 'oldest' ? new Date(a.date) - new Date(b.date) : a.category.localeCompare(b.category))
  const hasFilters = query || category !== 'All categories' || location !== 'All locations' || date
  const clearFilters = () => { setQuery(''); setCategory('All categories'); setLocation('All locations'); setDate('') }
  return <section className="explore-section"><div className="filter-bar"><label className="search-field"><Search size={17} /><span className="sr-only">Search receipts</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search the archive..." /></label><label className="select-field"><Filter size={16} /><span className="sr-only">Filter by category</span><select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label className="select-field"><MapPin size={16} /><span className="sr-only">Filter by location</span><select value={location} onChange={(event) => setLocation(event.target.value)}>{locations.map((item) => <option key={item}>{item}</option>)}</select></label><label className="date-field"><CalendarDays size={16} /><span className="sr-only">Filter by date</span><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="select-field"><span className="sr-only">Sort receipts</span><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="category">By category</option></select></label></div><div className="results-line"><span>{filtered.length} {filtered.length === 1 ? 'receipt' : 'receipts'} found</span>{hasFilters && <button className="text-button" onClick={clearFilters}>Clear filters <X size={14} /></button>}</div>{filtered.length ? <div className="receipt-grid">{filtered.map((receipt, index) => <ReceiptCard key={receipt.id} receipt={receipt} onSelect={onSelect} index={index} />)}</div> : <EmptyState />}</section>
}
function ReceiptCard({ receipt, onSelect, index = 0 }) { const [image, setImage] = useState(getReceiptImage(receipt.category)); return <motion.article className="receipt-card" style={{ '--stagger': `${Math.min(index, 8) * 45}ms` }} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .32, delay: Math.min(index, 8) * .045 }} whileHover={{ y: -5 }}><div className="receipt-image-wrap"><img className="receipt-image" src={image} alt={getImageAlt(receipt.category)} loading="eager" onError={() => setImage('/images/archive.svg')} /><span className={`category-pill ${categoryColor[receipt.category] || 'sage'}`}>{receipt.category}</span></div><div className="card-top"><span className="card-date">{formatDate(receipt.date, { month: 'short', day: 'numeric' })}</span></div><h3>{receipt.title}</h3><p>{receipt.description}</p><div className="card-footer"><span>{receipt.location || 'No location'}</span><motion.button className="small-button" onClick={() => onSelect(receipt)} aria-label={`Open details for ${receipt.title}`} whileHover={{ x: 3 }} whileTap={{ scale: .95 }}>Open <ArrowUpRight size={14} /></motion.button></div></motion.article> }
function EmptyState() { return <div className="empty-state"><FileText size={25} /><h3>No receipts in this pocket</h3><p>Try a different search or clear the active filters.</p></div> }

function Timeline({ receipts: items, onSelect }) {
  const grouped = items.filter((item) => item.date).sort((a, b) => new Date(b.date) - new Date(a.date)).reduce((groups, item) => { const key = formatDate(item.date, { month: 'long', year: 'numeric' }); (groups[key] ||= []).push(item); return groups }, {})
  return <section className="timeline-page"><div className="timeline-intro"><span className="category-pill sage">{items.length} dated moments</span><p>Chronology is one lens, not the whole story. Open a receipt to follow the evidence into its related moments.</p></div><div className="timeline">{Object.entries(grouped).map(([month, monthItems]) => <motion.div className="timeline-month" key={month} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: .3 }}><div className="timeline-month-label"><span className="timeline-pip" />{month}</div><div className="timeline-items">{monthItems.map((receipt, index) => <motion.button className="timeline-item" key={receipt.id} onClick={() => onSelect(receipt)} initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .3, delay: index * .06 }} whileHover={{ x: 5 }} whileTap={{ scale: .99 }}><motion.span className={`timeline-icon ${categoryColor[receipt.category] || 'sage'}`} whileHover={{ scale: 1.12 }}>{receipt.category.slice(0, 1)}</motion.span><span className="timeline-copy"><strong>{receipt.title}</strong><small>{formatDate(receipt.date, { weekday: 'short', month: 'short', day: 'numeric' })} · {formatTime(receipt.date)}{receipt.location ? ` · ${receipt.location}` : ''}</small><em>{receipt.description}</em></span><ChevronRight size={16} /></motion.button>)}</div></motion.div>)}</div></section>
}

function Connections({ receipts: items, onSelect }) { const [active, setActive] = useState(items[0]); const links = getConnections(active, items); return <section><div className="connection-layout"><div className="connection-list"><p className="eyebrow">Choose a starting point</p>{items.map((item) => <motion.button className={`connection-item ${active.id === item.id ? 'active' : ''}`} key={item.id} onClick={() => setActive(item)} whileTap={{ scale: .98 }}><span className={`category-dot ${categoryColor[item.category] || 'sage'}`} /><span><strong>{item.title}</strong><small>{item.category} · {formatDate(item.date, { month: 'short', day: 'numeric' })}</small></span><ChevronRight size={15} /></motion.button>)}</div><motion.div className="connection-stage" key={active.id} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: .3 }}><div className="stage-intro"><span className="category-pill sage">Evidence map</span><h2>{active.title}</h2><p>These moments connect through explicit matching rules. Nothing is inferred beyond what the records share.</p></div><div className="connection-center"><motion.span className={`big-node ${categoryColor[active.category] || 'sage'}`} initial={{ scale: .8, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ duration: .35 }}>{active.category.slice(0, 1)}</motion.span><div className="connection-spokes">{links.map(({ receipt, reasons }, index) => <motion.button key={receipt.id} className={`linked-node node-${index}`} onClick={() => onSelect(receipt)} initial={{ opacity: 0, scale: .85 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: index * .07, duration: .28 }} whileHover={{ scale: 1.04 }}><span className={`node-dot ${categoryColor[receipt.category] || 'sage'}`}>{receipt.category.slice(0, 1)}</span><strong>{receipt.title}</strong><small>{reasons.join(' · ')}</small></motion.button>)}</div>{!links.length && <p className="empty-inline">No matching location, tags, category, or nearby dates yet.</p>}</div><div className="rule-note"><Network size={15} /><span><strong>How links are made</strong> Shared location, matching tags, same category, or dates within three days.</span></div></motion.div></div></section> }

function Chapters({ receipts: items, onSelect, onNavigate }) { const groups = [{ title: 'Moments around Cedar Street', summary: 'These records share a location and happened within the same afternoon.', filter: (item) => item.location === 'Cedar Street' }, { title: 'The creative thread', summary: 'A set of moments connected by the shared “creative” tag.', filter: (item) => item.tags.includes('creative') }, { title: 'Evenings at home', summary: 'Notes, music, and searches recorded at Home after sunset.', filter: (item) => item.location === 'Home' && new Date(item.date).getHours() >= 18 }].map((group) => ({ ...group, receipts: items.filter(group.filter) })).filter((group) => group.receipts.length)
  return <section className="chapter-grid">{groups.map((group, index) => { const cover = group.receipts[0]; return <motion.article className="chapter-card" key={group.title} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .35, delay: index * .08 }} whileHover={{ y: -4 }}><div className="chapter-cover"><img src={getReceiptImage(cover.category)} alt={getImageAlt(cover.category, `decorative cover for ${group.title}`)} loading="lazy" /></div><div className="chapter-number">0{index + 1}</div><p className="eyebrow">Chapter {index + 1} · {group.receipts.length} moments</p><h2>{group.title}</h2><p>{group.summary}</p><div className="chapter-items">{group.receipts.slice(0, 3).map((receipt) => <button key={receipt.id} onClick={() => onSelect(receipt)}><span className={`category-dot ${categoryColor[receipt.category] || 'sage'}`} /><span>{receipt.title}</span><ChevronRight size={14} /></button>)}</div><button className="text-button" onClick={() => onNavigate('explore')}>Explore chapter <ArrowUpRight size={15} /></button></motion.article> })}</section> }

function Insights({ receipts: items, insights }) { const maxCategory = Math.max(...Object.values(insights.categories)); const maxLocation = Math.max(...Object.values(insights.locations)); const tagEntries = Object.entries(insights.tags).sort((a, b) => b[1] - a[1]).slice(0, 8); return <section className="insights-grid"><article className="insight-panel wide"><div className="panel-heading"><div><p className="eyebrow">Distribution</p><h2>Categories in the archive</h2></div><BarChart3 size={20} /></div><div className="bar-chart">{Object.entries(insights.categories).sort((a, b) => b[1] - a[1]).map(([label, value]) => <div className="bar-row" key={label}><span>{label}</span><div className="bar-track"><i style={{ width: `${(value / maxCategory) * 100}%` }} /></div><strong>{value}</strong></div>)}</div></article><article className="insight-panel"><div className="panel-heading"><div><p className="eyebrow">Places</p><h2>Where moments happen</h2></div></div><div className="location-list">{Object.entries(insights.locations).sort((a, b) => b[1] - a[1]).map(([label, value]) => <div key={label}><span>{label}</span><strong style={{ width: `${(value / maxLocation) * 100}%` }}>{value}</strong></div>)}</div></article><article className="insight-panel"><div className="panel-heading"><div><p className="eyebrow">Language</p><h2>Recurring tags</h2></div></div><div className="tag-cloud">{tagEntries.map(([tag, value]) => <span key={tag} style={{ '--tag-size': `${0.75 + value * 0.1}rem` }}>{tag} <b>{value}</b></span>)}</div></article>{insights.amountTotal !== null && <article className="insight-panel amount-panel"><p className="eyebrow">Recorded purchases</p><strong>${insights.amountTotal.toFixed(2)}</strong><p>Only records with a numeric amount are included.</p></article>}</section> }

function ReceiptModal({ receipt, receipts: items, onClose, onSelect, surprised }) { const related = getConnections(receipt, items, 3); return <motion.div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: .22 }}><motion.section className={`receipt-modal ${surprised ? 'surprise-result' : ''}`} role="dialog" aria-modal="true" aria-labelledby="receipt-title" initial={{ opacity: 0, y: 14, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 8, scale: .98 }} transition={{ duration: .3, ease: 'easeOut' }}><button className="modal-close icon-button" onClick={onClose} aria-label="Close receipt details"><X size={19} /></button>{surprised && <span className="surprise-label"><Shuffle size={13} /> A small discovery</span>}<span className={`category-pill ${categoryColor[receipt.category] || 'sage'}`}>{receipt.category}</span><p className="modal-date">{formatDate(receipt.date)} · {formatTime(receipt.date)}</p><h2 id="receipt-title">{receipt.title}</h2><p className="modal-description">{receipt.description}</p><dl className="detail-list">{receipt.location && <div><dt>Location</dt><dd>{receipt.location}</dd></div>}{receipt.tags.length > 0 && <div><dt>Tags</dt><dd>{receipt.tags.join(' · ')}</dd></div>}{Object.entries(receipt.metadata).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl>{related.length > 0 && <div className="related-block"><p className="eyebrow">Explore related moments</p>{related.map(({ receipt: item, reasons }) => <motion.button className="related-row" key={item.id} onClick={() => onSelect(item)} whileHover={{ x: 4 }}><span><strong>{item.title}</strong><small>{reasons.join(' · ')}</small></span><ChevronRight size={16} /></motion.button>)}</div>}</motion.section></motion.div> }

export default App
